用Numpy实现class05中讲到的神经网络

In [1]:
import numpy as np

In [2]:
def ReLU(Matrix):
   return np.maximum(0,Matrix)

In [3]:
X=np.array([[0.1],[0.2]])
print('输入X=')
print(X)

输入X=
[[0.1]
 [0.2]]


隐藏层参数

In [4]:
W1 = np.array([[-3, -2, -1], [0, 1, 2]])
b1 = np.array([-0.2, 0.3, -0.1])
print('W1=')
print(W1)
print('b1=')
print(b1)

W1=
[[-3 -2 -1]
 [ 0  1  2]]
b1=
[-0.2  0.3 -0.1]


计算隐藏层神经元输出

In [5]:
O1 = ReLU( np.dot(X.transpose(), W1) + b1 )
print('隐藏层神经元输出=')
print(O1)

隐藏层神经元输出=
[[0.  0.3 0.2]]


输出层参数

In [6]:
W2 = np.array([[-2, -1], [0, 1], [2, 3]])
b2 = np.array([0.1, -0.1])
print('W2=')
print(W2)
print('b2=')
print(b2)

W2=
[[-2 -1]
 [ 0  1]
 [ 2  3]]
b2=
[ 0.1 -0.1]


输出层神经元的输出

In [7]:
Y = ReLU( np.dot(O1, W2) + b2 )
print('输出层神经元的输出=')
print(Y)

输出层神经元的输出=
[[0.5 0.8]]
